#!/bin/sh
# yasui-runner installer — served verbatim at https://yasui.io/runner.sh (04 §4).
#
#   curl -fsSL https://yasui.io/runner.sh | sh
#
# POSIX sh, idempotent (re-run = upgrade). Installs @yasui.io/runner into a
# PRIVATE npm prefix (~/.yasui-runner/tool) — never `npm i -g`, no sudo, ever.
# Pin a version with:  YASUI_RUNNER_VERSION=0.3.1 sh runner.sh

set -eu

YASUI_HOME="${YASUI_RUNNER_HOME:-$HOME/.yasui-runner}"
PKG_VERSION="${YASUI_RUNNER_VERSION:-latest}"
NODE_VERSION="v22.14.0"

# --- sha256 pins for the pinned Node runtime (one per platform/arch tuple) ---
# PLACEHOLDER: these pins are regenerated by .github/workflows/release.yml for
# every release from https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt
# (see the "pin-node-hashes" step). An unset pin fails closed.
NODE_SHA256_DARWIN_ARM64="__RELEASE_YML_PIN_DARWIN_ARM64__"
NODE_SHA256_DARWIN_X64="__RELEASE_YML_PIN_DARWIN_X64__"
NODE_SHA256_LINUX_ARM64="__RELEASE_YML_PIN_LINUX_ARM64__"
NODE_SHA256_LINUX_X64="__RELEASE_YML_PIN_LINUX_X64__"

info() { printf '\033[1;34m==>\033[0m %s\n' "$1"; }
fail() { printf '\033[1;31merror:\033[0m %s\n' "$1" >&2; exit 1; }

# 1. Platform detect (04 §4.1).
OS_NAME="$(uname -s)"
ARCH_NAME="$(uname -m)"
case "$OS_NAME" in
  Darwin) PLATFORM="darwin" ;;
  Linux)  PLATFORM="linux" ;;
  *) fail "v1 supports macOS and Linux on arm64/x64 (got: $OS_NAME). On Windows, use WSL2 and re-run inside it." ;;
esac
case "$ARCH_NAME" in
  arm64|aarch64) ARCH="arm64" ;;
  x86_64|amd64)  ARCH="x64" ;;
  *) fail "v1 supports macOS and Linux on arm64/x64 (got: $ARCH_NAME)." ;;
esac
if [ "$PLATFORM" = "linux" ] && grep -qi microsoft /proc/version 2>/dev/null; then
  info "WSL detected — continuing (the runner runs fine inside WSL2)."
fi

# 2. Dependency check: git >= 2.30 (GitService, 04 §10).
command -v git >/dev/null 2>&1 || fail "git is required (>= 2.30). macOS: xcode-select --install · Debian/Ubuntu: apt install git"
GIT_VER="$(git --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')"
GIT_MAJOR="$(printf '%s' "$GIT_VER" | cut -d. -f1)"
GIT_MINOR="$(printf '%s' "$GIT_VER" | cut -d. -f2)"
if [ "$GIT_MAJOR" -lt 2 ] || { [ "$GIT_MAJOR" -eq 2 ] && [ "$GIT_MINOR" -lt 30 ]; }; then
  fail "git >= 2.30 required (found $GIT_VER)"
fi

# 3. Node resolution: system node >= 20, else pinned Node 22 LTS into runtime/ (04 §4.3).
NODE_BIN=""
if command -v node >/dev/null 2>&1; then
  NODE_MAJOR="$(node -e 'process.stdout.write(String(process.versions.node.split(".")[0]))' 2>/dev/null || echo 0)"
  if [ "$NODE_MAJOR" -ge 20 ]; then
    NODE_BIN="$(command -v node)"
    info "using system node $(node --version)"
  fi
fi

if [ -z "$NODE_BIN" ]; then
  NODE_DIR="$YASUI_HOME/runtime/node-$NODE_VERSION"
  NODE_BIN="$NODE_DIR/bin/node"
  if [ ! -x "$NODE_BIN" ]; then
    info "downloading Node $NODE_VERSION ($PLATFORM-$ARCH) to $NODE_DIR"
    case "$PLATFORM-$ARCH" in
      darwin-arm64) NODE_SHA="$NODE_SHA256_DARWIN_ARM64" ;;
      darwin-x64)   NODE_SHA="$NODE_SHA256_DARWIN_X64" ;;
      linux-arm64)  NODE_SHA="$NODE_SHA256_LINUX_ARM64" ;;
      linux-x64)    NODE_SHA="$NODE_SHA256_LINUX_X64" ;;
    esac
    case "$NODE_SHA" in
      __RELEASE_YML_PIN_*) fail "this copy of runner.sh has no Node sha256 pins (unreleased build). Install Node >= 20 yourself and re-run." ;;
    esac
    TARBALL="node-$NODE_VERSION-$PLATFORM-$ARCH.tar.gz"
    TMP_DIR="$(mktemp -d)"
    curl -fsSL "https://nodejs.org/dist/$NODE_VERSION/$TARBALL" -o "$TMP_DIR/$TARBALL"
    # sha256 verification against the inline pin (04 §4.3).
    if command -v shasum >/dev/null 2>&1; then
      ACTUAL_SHA="$(shasum -a 256 "$TMP_DIR/$TARBALL" | cut -d' ' -f1)"
    else
      ACTUAL_SHA="$(sha256sum "$TMP_DIR/$TARBALL" | cut -d' ' -f1)"
    fi
    [ "$ACTUAL_SHA" = "$NODE_SHA" ] || fail "Node tarball sha256 mismatch (expected $NODE_SHA, got $ACTUAL_SHA)"
    mkdir -p "$NODE_DIR"
    tar -xzf "$TMP_DIR/$TARBALL" -C "$NODE_DIR" --strip-components=1
    rm -rf "$TMP_DIR"
  fi
  info "using pinned node $("$NODE_BIN" --version)"
fi
NODE_DIR_BIN="$(dirname "$NODE_BIN")"
NPM_BIN="$NODE_DIR_BIN/npm"
command -v "$NPM_BIN" >/dev/null 2>&1 || NPM_BIN="npm"

# 4. Install into the private prefix (04 §4.4).
mkdir -p "$YASUI_HOME/tool" "$YASUI_HOME/bin" "$YASUI_HOME/logs" "$YASUI_HOME/state"
chmod 700 "$YASUI_HOME"
info "installing @yasui.io/runner@$PKG_VERSION into $YASUI_HOME/tool"
"$NPM_BIN" install --prefix "$YASUI_HOME/tool" --no-fund --no-audit "@yasui.io/runner@$PKG_VERSION"

# 5. Shim + PATH (04 §4.5) — with the tool.prev crash fallback (04 §12 step 5).
SHIM="$YASUI_HOME/bin/yasui-runner"
cat > "$SHIM" <<EOF
#!/bin/sh
# yasui-runner shim (generated by runner.sh)
YASUI_HOME="\${YASUI_RUNNER_HOME:-\$HOME/.yasui-runner}"
ENTRY="\$YASUI_HOME/tool/node_modules/@yasui.io/runner/dist/cli/index.js"
PREV_ENTRY="\$YASUI_HOME/tool.prev/node_modules/@yasui.io/runner/dist/cli/index.js"
CRASH_LOG="\$YASUI_HOME/state/crash.log"
# Fall back to tool.prev when tool/ is missing, or when the new version crashed
# twice within 60 s (self-update rollback, 04 §12).
if [ ! -f "\$ENTRY" ] && [ -f "\$PREV_ENTRY" ]; then ENTRY="\$PREV_ENTRY"; fi
if [ -f "\$CRASH_LOG" ] && [ -f "\$PREV_ENTRY" ]; then
  NOW=\$(date +%s)
  RECENT=\$(awk -v now="\$NOW" 'now - \$1 < 60' "\$CRASH_LOG" 2>/dev/null | wc -l | tr -d ' ')
  if [ "\$RECENT" -ge 2 ]; then
    echo "yasui-runner: new version crashed twice within 60s — falling back to tool.prev" >&2
    ENTRY="\$PREV_ENTRY"
  fi
fi
if [ "\$1" = "start" ]; then
  # No exec for start: record crash times so the shim can roll back (04 §12).
  "$NODE_BIN" "\$ENTRY" "\$@"
  CODE=\$?
  if [ "\$CODE" -ne 0 ]; then date +%s >> "\$CRASH_LOG"; fi
  exit "\$CODE"
fi
exec "$NODE_BIN" "\$ENTRY" "\$@"
EOF
chmod 755 "$SHIM"

ON_PATH=0
case ":$PATH:" in *":$HOME/.local/bin:"*) ON_PATH=1 ;; esac
if [ -d "$HOME/.local/bin" ] && [ "$ON_PATH" = "1" ]; then
  ln -sf "$SHIM" "$HOME/.local/bin/yasui-runner"
  info "symlinked into ~/.local/bin/yasui-runner"
else
  printf '\nadd this to your shell profile:\n  export PATH="%s:$PATH"\n\n' "$YASUI_HOME/bin"
fi

# 6. Finish (04 §4.6).
INSTALLED_VERSION="$("$SHIM" --version 2>/dev/null || echo unknown)"
info "installed yasui-runner $INSTALLED_VERSION"
printf '\nnext step — mint a pairing code at https://yasui.io/dashboard/agents, then:\n\n  yasui-runner connect --code XXXX-XXXX\n\n'
